# <<BEGIN-copyright>>
# <<END-copyright>>

.PHONY: default check clean realclean

Executables = $(CppSource:.cpp=)

local_CXXFLAGS += -I$(GIDI_PATH)/Test/Utilities $(LIB_PATHS) -L$(GIDI_PATH)/Test/Utilities

LIBS = -lHAPI -lLUPI -lpugixml -lnumericalfunctions -lstatusMessageReporting -lm $(HDF5_LIBS)

default: $(Executables)

$(Executables): %: %.cpp ../../../include/*.h* ../../../lib/*.a
	$(CXX) $(local_CXXFLAGS) $< -o $@ $(LIBS)

clean:
	rm -rf $(Executables) $(Archive) *.o Outputs file1 file2

realclean: clean
	rm -rf *.dSYM
