# <<BEGIN-copyright>>
# Copyright 2019, Lawrence Livermore National Security, LLC.
# See the top-level COPYRIGHT file for details.
# 
# SPDX-License-Identifier: MIT
# <<END-copyright>>

sourceDir = ../Src

.PHONY: default clean realclean

default:
	cp $(sourceDir)/nf_utilities.h .

clean:
	rm -f *.h

realclean: clean
