# <<BEGIN-copyright>>
# <<END-copyright>>

.PHONY: default check clean realclean

PYTHON = python3

Executables = $(CppSource:.cpp=)

local_CXXFLAGS += -I$(GIDI_PATH)/Test/Utilities -I$(MCGIDI_PATH)/Test/Utilities
ifndef COMPILE_UTILITIES
    local_CXXFLAGS += $(LIB_PATHS) -L$(GIDI_PATH)/Test/Utilities -L$(MCGIDI_PATH)/Test/Utilities
endif

LIBS =  -lGIDI_testUtilities -lMCGIDI_testUtilities -lMCGIDI -lGIDI -lPoPI -lGUPI -lHAPI -lRISI -lLUPI \
        -lnumericalfunctions -lstatusMessageReporting -lpugixml -lexpat -lm $(HDF5_LIBS)

default: $(Executables)

$(Executables): %: %.cpp ../../../include/*.h* ../../../lib/*.a
	$(CXX) $(local_CXXFLAGS) $< -o $@ $(LIBS)

clean:
	rm -rf $(Executables) $(Archive) *.o Outputs file1 file2

realclean: clean
	rm -rf *.dSYM
