# <<BEGIN-copyright>>
# <<END-copyright>>

.PHONY: default check clean realclean

Executables = $(CppSource:.cpp=)

local_CXXFLAGS = $(CXXFLAGS) \
        -I$(MCGIDI_PATH)/include 		-I$(MCGIDI_PATH)/Test/Utilities 	-I$(GIDI_PATH)/include \
        -I$(GIDI_PATH)/Test/Utilities 	-I$(POPI_INCLUDE) 					-I$(SMR_INCLUDE) \
        -I$(NF_INCLUDE) 				-I$(PUGIXML_INCLUDE) 

LIBS =  -L$(GIDI_PATH)/Test/Utilities -lGIDI_testUtilities \
		-L$(MCGIDI_PATH)/Test/Utilities -lMCGIDI_testUtilities \
		-L$(MCGIDI_PATH)/lib -lMCGIDI \
		-L$(GIDI_PATH)/lib -lGIDI \
		-L$(POPI_LIB) -lPoPI \
		-L$(SMR_LIB) -lstatusMessageReporting \
		-L$(NF_LIB) -lnumericalfunctions \
		-L$(PUGIXML_LIB) -lpugixml -lexpat

default: $(Executables)

$(Executables): %: %.cpp
	$(CXX) $(local_CXXFLAGS) $< -o $@ $(LIBS)

clean:
	rm -rf $(Executables) $(Archive) *.o Outputs file1 file2

realclean: clean
	rm -rf *.dSYM
