# <<BEGIN-copyright>>
# Copyright 2019, Lawrence Livermore National Security, LLC.
# See the top-level COPYRIGHT file for details.
# 
# SPDX-License-Identifier: MIT
# <<END-copyright>>

SHELL = /bin/sh

.PHONY: clean realclean

default:
	cp ../Src/statusMessageReporting.h .

clean:
	rm -f statusMessageReporting.h

realclean: clean
