# <<BEGIN-copyright>>
# Copyright 2019, Lawrence Livermore National Security, LLC.
# See the top-level COPYRIGHT file for details.
# 
# SPDX-License-Identifier: MIT
# <<END-copyright>>

PYTHON = python

.PHONY: default check clean realclean

default:

check:
	$(PYTHON) comparing.py

clean:

realclean: clean
