# <<BEGIN-copyright>>
# <<END-copyright>>

.PHONY: default check clean realclean

Executables = $(CppSource:.cpp=)

local_CXXFLAGS2 := $(local_CXXFLAGS) -I$(GIDI_PATH)/Test/Utilities -I$(MCGIDI_PATH)/Test/Utilities -I$(MCGIDI_PATH)/Speeds/Utilities
local_CXXFLAGS = $(local_CXXFLAGS2) $(LIB_PATHS) -L$(GIDI_PATH)/Test/Utilities -L$(MCGIDI_PATH)/Test/Utilities -L$(MCGIDI_PATH)/Speeds/Utilities

LIBS =  -lGIDI_testUtilities -lMCGIDI_testUtilities -lutilities4Speed -lMCGIDI -lGIDI -lPoPI -lRISI -lGUPI -lHAPI -lLUPI \
		-lnumericalfunctions -lstatusMessageReporting -lpugixml -lexpat -lm $(HDF5_LIBS)

default: $(Executables)

$(Executables): %: %.cpp ../../../include/*.h* ../../../lib/*.a
	echo "    "$@
	$(CXX) $(local_CXXFLAGS) $< -o $@ $(LIBS)

clean:
	rm -rf $(Executables) $(Archive) *.o *.out

realclean: clean
	rm -rf *.dSYM
