# <<BEGIN-copyright>>
# <<END-copyright>>

.PHONY: default check clean realclean

Executables = $(CppSource:.cpp=)

local_CXXFLAGS += -I$(GIDI_PATH)/Test/Utilities
ifndef COMPILE_UTILITIES
    local_CXXFLAGS += $(LIB_PATHS) -L$(GIDI_PATH)/Test/Utilities
endif

LIBS = -lGIDI_testUtilities -lGIDI -lPoPI -lHAPI -lLUPI -lnumericalfunctions -lstatusMessageReporting -lpugixml -lexpat -lm $(HDF5_LIBS)

default: $(Executables)

$(Executables): %: %.cpp
	$(CXX) $(local_CXXFLAGS) $< -o $@ $(LIBS)

clean:
	rm -rf $(Executables) $(Archive) *.o Outputs file1 file2

realclean: clean
	rm -rf *.dSYM
