# <<BEGIN-copyright>>
# Copyright 2019, Lawrence Livermore National Security, LLC.
# See the top-level COPYRIGHT file for details.
# 
# SPDX-License-Identifier: MIT
# <<END-copyright>>

.PHONY: default headers clean realclean

default: headers

headers:
	cp ../Src/*.hpp .

clean:
	rm -f *.hpp

realclean: clean
