# <<BEGIN-copyright>>
# Copyright 2019, Lawrence Livermore National Security, LLC.
# See the top-level COPYRIGHT file for details.
# 
# SPDX-License-Identifier: MIT
# <<END-copyright>>

SHELL = /bin/sh

sourceDir = ../Src

.PHONY: headers clean realclean

headers:
	cp $(sourceDir)/nf_Legendre.h .

clean:
	rm -f *.h

realclean: clean
