# <<BEGIN-copyright>>
# <<END-copyright>>

.PHONY: default check clean realclean

Executables = $(CppSource:.cpp=)

local_CXXFLAGS = $(CXXFLAGS) \
        -I$(PUGIXML_PATH)/include -L$(PUGIXML_PATH)/lib \
        -I$(POPI_INCLUDE) -L$(POPI_LIB)

LIBS = -lPoPI -lpugixml

default: $(Executables)

$(Executables): %: %.cpp
	$(CXX) $(local_CXXFLAGS) $< -o $@ $(LIBS)

clean:
	rm -rf $(Executables) $(Archive) *.o Outputs file1 file2

realclean: clean
	rm -rf *.dSYM
