# <<BEGIN-copyright>>
# <<END-copyright>>

.PHONY: default check clean realclean

Executables = $(CppSource:.cpp=)

local_CXXFLAGS += $(LIB_PATHS)

LIBS = -lPoPI -lHAPI -lLUPI -lnumericalfunctions -lstatusMessageReporting -lpugixml -lm $(HDF5_LIBS)

default: $(Executables)

$(Executables): %: %.cpp ../../../include/*.h* ../../../lib/*.a
	$(CXX) $(local_CXXFLAGS) $< -o $@ $(LIBS)

clean:
	rm -rf $(Executables) $(Archive) *.o Outputs file1 file2

realclean: clean
	rm -rf *.dSYM
