SHELL = /bin/bash

# <<BEGIN-copyright>>
# <<END-copyright>>

.PHONY: default include clean realclean

DIRS = statusMessageReporting PoPsCpp numericalFunctions pugixml

default: include

include:
	cp ../popskit_version.h .
	for DIR in $(DIRS); do cd ../$$DIR/; $(MAKE) include; done
	for DIR in $(DIRS); do cp ../$$DIR/include/*.h* .; done

clean:
	rm -f *.h *.hpp

realclean: clean
