SHELL = /bin/ksh

# <<BEGIN-copyright>>
# Copyright 2019, Lawrence Livermore National Security, LLC.
# See the top-level COPYRIGHT file for details.
# 
# SPDX-License-Identifier: MIT
# <<END-copyright>>

DIRS = doxygen

.PHONY: default check clean realclean

default:

check:

clean:

realclean:
	rm -rf html  latex  xml
