name: GIDIplus build + check

on:
  push:
    branches: [ "master", "ci_dev" ]
  pull_request:
    branches: [ "master" ]

env:
  cppflags: "-std=c++17 -Wall -Wpedantic -Wshadow -Wstrict-aliasing -Wdelete-non-virtual-dtor -Wfloat-conversion -ffp-contract=off -funroll-loops -finline-functions -DMCGIDI_USE_DOUBLES"

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        compiler: [ {cpp: g++, cc: gcc}, {cpp: clang++, cc: clang} ]

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Build
      run: |
        curl -L -o Misc/pugixml-1.13.zip https://github.com/zeux/pugixml/releases/download/v1.13/pugixml-1.13.zip
        make -s -j all CXX=${{ matrix.compiler.cpp }} CC=${{ matrix.compiler.cc }} CXXFLAGS="$cppflags"
      shell: bash

    - name: Run check
      run: |
        cd GIDI/Test
        curl -L -o Data.tar.gz https://github.com/LLNL/gidiplus/releases/download/v3.33.0/testData_3.33.0.tar.gz
        tar -xf Data.tar.gz
        cd -
        make -s -j check CXX=${{ matrix.compiler.cpp }} CC=${{ matrix.compiler.cc }} CXXFLAGS="$cppflags"
      shell: bash

