name: GIDIplus build + check

on:
  push:
    branches: [ "master", "ci_dev" ]
  pull_request:
    branches: [ "master" ]

env:
  cppflags: "-std=c++17 -Wall -Wpedantic -Wshadow -Wstrict-aliasing -Wdelete-non-virtual-dtor -Wfloat-conversion -ffp-contract-off -funroll-loops -finline-functions"

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        compiler: [g++, clang++]

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: |
        curl -L -o Misc/pugixml-1.13.zip https://github.com/zeux/pugixml/releases/download/v1.13/pugixml-1.13.zip
        make -s -j all CXX=${{ matrix.compiler }} CXXFLAGS="$cppflags"

    - name: Run check
      run: |
        cd GIDI/Test
        curl -L -o Data.tar.gz https://github.com/LLNL/gidiplus/releases/download/v3.25.7/testData_3.25.7.tar.gz
        tar -xf Data.tar.gz
        cd -
        make -s -j check CXX=${{ matrix.compiler }} CXXFLAGS="$cppflags"
      shell: bash

